# Generated by Django 4.2.3 on 2023-12-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_comment_ad_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
